### ISSUE TITLE
Campo CbteTipo no se corresponde con alguno de los comprobantes habilitados en FEParamGetTiposCbte"

### ISSUE THREAD

**Issue by melaernst** [reingart/pyafipws#39]
Gente tengo este error 
Campo CbteTipo no se corresponde con alguno de los comprobantes habilitados en FEParamGetTiposCbte"
y no se como solucionarlo, alguna idea???

**Comment by fjbardelli** [comment]
Le debes estar mandando el tipo de comprobante, por ejemplo 1 Fac A, 19 fac
E.

**Comment by melaernst** [comment]
Claro el tema es que necesito para factura T ahora que es para turismo y es la 195, no se si me falta actualizar algo, yo lo hice igual que la factura A pero cambie los valores

**Comment by fjbardelli** [comment]
Nunca trabaje con fac T, habría que revisar la Doc, a ver si que sea T no
obliga a algunos campos obligatorios o con valores específicos

El 15 nov. 2017 21:50, "Melanie Ernst" <notifications@github.com> escribió:

Claro el tema es que necesito para factura T ahora que es para turismo y es
la 195, no se si me falta actualizar algo, yo lo hice igual que la factura
A pero cambie los valores

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/reingart/pyafipws/issues/39#issuecomment-344779042>,
or mute
the thread

**Comment by reingart** [comment]
La factura T es otro webservice: [WSCT](http://www.sistemasagiles.com.ar/trac/wiki/FacturaElectronicaComprobantesTurismo)

**Comment by mpastorini9** [comment]
> Gente tengo este error Campo CbteTipo no se corresponde con alguno de los comprobantes habilitados en FEParamGetTiposCbte" y no se como solucionarlo, alguna idea???

5 años mas tarde tengo el mismo problema con una nota de credito de exportacion, cual fue la solucion a tu problema? ya lo intente todo.
